# Generated by Django 3.1.4 on 2020-12-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201230_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
