# Generated by Django 3.1.6 on 2021-02-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210207_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Not paid'), ('P', 'Paid'), ('D', 'Delivered')], default='NP', max_length=10),
        ),
    ]
