# Generated by Django 3.1.6 on 2021-02-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210213_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.TextField(null=True, unique=True),
        ),
    ]
