# Generated by Django 3.1.5 on 2021-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210131_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/2021/02/'),
        ),
        migrations.AlterField(
            model_name='productthumbnail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_thumbnails/2021/02/'),
        ),
    ]
